### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by kingdotIO** [GoldenDrakeStudios/golden-drake-linux#2]
Suggestions, the Luks on lvm is Data-at-rest, which is not very secure, it should be FDE, also btrfs is already a better lvm2, btrfs subvolumes actually out perform lvm logical volumes, BTRFS should NEVER go on lvm for that reason as well as when it's stacked it weighs down the machine, and finally this installer doesn't allow more than 1 drive at a time, personally I prefer having the boot/efi partition on a USB that should the time come, I hide it, rendering the hard drive inaccessible without. I Love the end result just a few issues that can easily fixed via command line installer or importing existing mount points.

**Comment by theDrake** [comment]
Thanks for the excellent ideas and feedback! We'll continue tweaking all the partitioning options and might completely overhaul some of them when we have time.
