### ISSUE TITLE
Auto Encryption with lvm.

### ISSUE THREAD

**Issue by kingdotIO** [GoldenDrakeStudios/golden-drake-linux#3]
Switch the initramfs to Dracut, you won't have an issue. With that recommended might I say you're playing with fire, Luks on LVM is widely known to be the weakest encryption, Each logical volume is essentially a different drive, proper Encryption is FDE, end to end, all lv's, btrfs subvolumes, or XFS subvolumes get mounted individually, when they should be under 1 massive 8308 or 8309 gdisk partition using LVM will hinder performance as well as take away what those fs are known for. Just a warning, cuz I saw the script, there's a lot of things that don't quite match any installation method I'm aware of, which scares me off.

**Comment by theDrake** [comment]
Once again, thank you so much for providing detailed, useful, excellent advice! We definitely want to improve (and perhaps diversify) various aspects of this installer, time permitting. Some of the code is carried over from [Anarchy](https://gitlab.com/anarchyinstaller/installer), of course, and though we have made significant modifications, additions, and subtractions, you are right to point out that a lot more could (and should) be done. We'll keep at it and will definitely consider every point you've raised!
